language: python

# Run jobs on container-based infrastructure, can be overridden per job

env:
  - PARALLELIZE=true

matrix:
  include:
    # Pip can use Travis build-in Python
      - python: 3.6
      - python: 3.7
        dist: xenial  # Travis Trusty image does not have Python 3.7, Xenial does
      - python: 3.8

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Install the package(s) locally
  - pip install -U pytest pytest-cov pytest-xdist codecov hypothesis
  - pip install -e .

script:
  - pytest --cov-report term-missing --cov=kda -v -n 4

notifications:
    email: false

after_success:
  - codecov
