name: Linux Python Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_kda:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest pytest-cov pytest-xdist hypothesis

      - name: Install kda
        run: |
          python -m pip install .

      - name: Test with pytest
        run: |
          pytest -v -n 10 --cov=./kda --cov-report=xml

      - name: Code Coverage
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
          fail_ci_if_error: True
          verbose: True
